import { posicionesIdentificadores } from './posiciones'
import { criteriosIdentificadores } from './criterios'

export const jugadores = [
  {
    nombre: 'Thiago Silva',
    foto: 'card-silva.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 7,
      [criteriosIdentificadores.TIROS]: 6,
      [criteriosIdentificadores.PASES_CORTOS]: 9,
      [criteriosIdentificadores.PASES_LARGOS]: 7,
      [criteriosIdentificadores.CENTROS]: 6,
      [criteriosIdentificadores.CONTROL_BALON]: 8,
      [criteriosIdentificadores.DEFINICION]: 7,
      [criteriosIdentificadores.VELOCIDAD]: 6,
      [criteriosIdentificadores.CREATIVIDAD]: 9,
      [criteriosIdentificadores.AMBIDIESTRO]: 5,
      [criteriosIdentificadores.ALTURA]: 7,
      [criteriosIdentificadores.RENDIMIENTO]: 8,
    },
  },
  {
    nombre: 'Presnel Kimpembe',
    foto: 'card-kimpembe.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 8,
      [criteriosIdentificadores.TIROS]: 5,
      [criteriosIdentificadores.PASES_CORTOS]: 5,
      [criteriosIdentificadores.PASES_LARGOS]: 4,
      [criteriosIdentificadores.CENTROS]: 4,
      [criteriosIdentificadores.CONTROL_BALON]: 8,
      [criteriosIdentificadores.DEFINICION]: 5,
      [criteriosIdentificadores.VELOCIDAD]: 9,
      [criteriosIdentificadores.CREATIVIDAD]: 4,
      [criteriosIdentificadores.AMBIDIESTRO]: 4,
      [criteriosIdentificadores.ALTURA]: 8,
      [criteriosIdentificadores.RENDIMIENTO]: 6,
    },
  },
  {
    nombre: 'Thilo Kehrer',
    foto: 'card-kherer.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 8,
      [criteriosIdentificadores.TIROS]: 8,
      [criteriosIdentificadores.PASES_CORTOS]: 8,
      [criteriosIdentificadores.PASES_LARGOS]: 10,
      [criteriosIdentificadores.CENTROS]: 5,
      [criteriosIdentificadores.CONTROL_BALON]: 8,
      [criteriosIdentificadores.DEFINICION]: 10,
      [criteriosIdentificadores.VELOCIDAD]: 7,
      [criteriosIdentificadores.CREATIVIDAD]: 4,
      [criteriosIdentificadores.AMBIDIESTRO]: 7,
      [criteriosIdentificadores.ALTURA]: 5,
      [criteriosIdentificadores.RENDIMIENTO]: 7,
    },
  },
  {
    nombre: 'Marquinhos',
    foto: 'card-marquinhos.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 9,
      [criteriosIdentificadores.TIROS]: 9,
      [criteriosIdentificadores.PASES_CORTOS]: 4,
      [criteriosIdentificadores.PASES_LARGOS]: 6,
      [criteriosIdentificadores.CENTROS]: 5,
      [criteriosIdentificadores.CONTROL_BALON]: 9,
      [criteriosIdentificadores.DEFINICION]: 10,
      [criteriosIdentificadores.VELOCIDAD]: 5,
      [criteriosIdentificadores.CREATIVIDAD]: 9,
      [criteriosIdentificadores.AMBIDIESTRO]: 6,
      [criteriosIdentificadores.ALTURA]: 10,
      [criteriosIdentificadores.RENDIMIENTO]: 10,
    },
  },
  {
    nombre: 'Thomas Meunier',
    foto: 'card-meunier.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 5,
      [criteriosIdentificadores.TIROS]: 9,
      [criteriosIdentificadores.PASES_CORTOS]: 6,
      [criteriosIdentificadores.PASES_LARGOS]: 5,
      [criteriosIdentificadores.CENTROS]: 6,
      [criteriosIdentificadores.CONTROL_BALON]: 4,
      [criteriosIdentificadores.DEFINICION]: 6,
      [criteriosIdentificadores.VELOCIDAD]: 10,
      [criteriosIdentificadores.CREATIVIDAD]: 8,
      [criteriosIdentificadores.AMBIDIESTRO]: 10,
      [criteriosIdentificadores.ALTURA]: 10,
      [criteriosIdentificadores.RENDIMIENTO]: 4,
    },
  },
  {
    nombre: 'Dani Alves',
    foto: 'card-alves.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 10,
      [criteriosIdentificadores.TIROS]: 4,
      [criteriosIdentificadores.PASES_CORTOS]: 6,
      [criteriosIdentificadores.PASES_LARGOS]: 7,
      [criteriosIdentificadores.CENTROS]: 7,
      [criteriosIdentificadores.CONTROL_BALON]: 10,
      [criteriosIdentificadores.DEFINICION]: 4,
      [criteriosIdentificadores.VELOCIDAD]: 4,
      [criteriosIdentificadores.CREATIVIDAD]: 7,
      [criteriosIdentificadores.AMBIDIESTRO]: 7,
      [criteriosIdentificadores.ALTURA]: 9,
      [criteriosIdentificadores.RENDIMIENTO]: 10,
    },
  },
  {
    nombre: 'Juan Bernat',
    foto: 'card-bernat.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 9,
      [criteriosIdentificadores.TIROS]: 6,
      [criteriosIdentificadores.PASES_CORTOS]: 10,
      [criteriosIdentificadores.PASES_LARGOS]: 8,
      [criteriosIdentificadores.CENTROS]: 8,
      [criteriosIdentificadores.CONTROL_BALON]: 9,
      [criteriosIdentificadores.DEFINICION]: 10,
      [criteriosIdentificadores.VELOCIDAD]: 4,
      [criteriosIdentificadores.CREATIVIDAD]: 7,
      [criteriosIdentificadores.AMBIDIESTRO]: 8,
      [criteriosIdentificadores.ALTURA]: 9,
      [criteriosIdentificadores.RENDIMIENTO]: 7,
    },
  },
  {
    nombre: 'Layvin Kurzawa',
    foto: 'card-kurzawa.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 10,
      [criteriosIdentificadores.TIROS]: 10,
      [criteriosIdentificadores.PASES_CORTOS]: 8,
      [criteriosIdentificadores.PASES_LARGOS]: 9,
      [criteriosIdentificadores.CENTROS]: 8,
      [criteriosIdentificadores.CONTROL_BALON]: 7,
      [criteriosIdentificadores.DEFINICION]: 5,
      [criteriosIdentificadores.VELOCIDAD]: 10,
      [criteriosIdentificadores.CREATIVIDAD]: 9,
      [criteriosIdentificadores.AMBIDIESTRO]: 5,
      [criteriosIdentificadores.ALTURA]: 4,
      [criteriosIdentificadores.RENDIMIENTO]: 9,
    },
  },
  {
    nombre: 'Colin Dagba',
    foto: 'card-dagba.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 6,
      [criteriosIdentificadores.TIROS]: 5,
      [criteriosIdentificadores.PASES_CORTOS]: 4,
      [criteriosIdentificadores.PASES_LARGOS]: 8,
      [criteriosIdentificadores.CENTROS]: 5,
      [criteriosIdentificadores.CONTROL_BALON]: 10,
      [criteriosIdentificadores.DEFINICION]: 7,
      [criteriosIdentificadores.VELOCIDAD]: 4,
      [criteriosIdentificadores.CREATIVIDAD]: 7,
      [criteriosIdentificadores.AMBIDIESTRO]: 9,
      [criteriosIdentificadores.ALTURA]: 4,
      [criteriosIdentificadores.RENDIMIENTO]: 10,
    },
  },
  {
    nombre: "Stanley N'Soki",
    foto: 'card-nsoki.png',
    posicion: posicionesIdentificadores.DEFENSA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 9,
      [criteriosIdentificadores.TIROS]: 8,
      [criteriosIdentificadores.PASES_CORTOS]: 9,
      [criteriosIdentificadores.PASES_LARGOS]: 9,
      [criteriosIdentificadores.CENTROS]: 4,
      [criteriosIdentificadores.CONTROL_BALON]: 7,
      [criteriosIdentificadores.DEFINICION]: 10,
      [criteriosIdentificadores.VELOCIDAD]: 7,
      [criteriosIdentificadores.CREATIVIDAD]: 10,
      [criteriosIdentificadores.AMBIDIESTRO]: 10,
      [criteriosIdentificadores.ALTURA]: 8,
      [criteriosIdentificadores.RENDIMIENTO]: 8,
    },
  },
  {
    nombre: 'Marco Verratti',
    foto: 'card-verratti.png',
    posicion: posicionesIdentificadores.MEDIOCAMPISTA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 5,
      [criteriosIdentificadores.TIROS]: 7,
      [criteriosIdentificadores.PASES_CORTOS]: 10,
      [criteriosIdentificadores.PASES_LARGOS]: 6,
      [criteriosIdentificadores.CENTROS]: 7,
      [criteriosIdentificadores.CONTROL_BALON]: 6,
      [criteriosIdentificadores.DEFINICION]: 5,
      [criteriosIdentificadores.VELOCIDAD]: 10,
      [criteriosIdentificadores.CREATIVIDAD]: 5,
      [criteriosIdentificadores.AMBIDIESTRO]: 8,
      [criteriosIdentificadores.ALTURA]: 9,
      [criteriosIdentificadores.RENDIMIENTO]: 6,
    },
  },
  {
    nombre: 'Angel Di María',
    foto: 'card-dimaria.png',
    posicion: posicionesIdentificadores.MEDIOCAMPISTA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 5,
      [criteriosIdentificadores.TIROS]: 5,
      [criteriosIdentificadores.PASES_CORTOS]: 7,
      [criteriosIdentificadores.PASES_LARGOS]: 4,
      [criteriosIdentificadores.CENTROS]: 7,
      [criteriosIdentificadores.CONTROL_BALON]: 8,
      [criteriosIdentificadores.DEFINICION]: 6,
      [criteriosIdentificadores.VELOCIDAD]: 8,
      [criteriosIdentificadores.CREATIVIDAD]: 5,
      [criteriosIdentificadores.AMBIDIESTRO]: 4,
      [criteriosIdentificadores.ALTURA]: 9,
      [criteriosIdentificadores.RENDIMIENTO]: 10,
    },
  },
  {
    nombre: 'Lassana Diarra',
    foto: 'card-diarra.png',
    posicion: posicionesIdentificadores.MEDIOCAMPISTA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 7,
      [criteriosIdentificadores.TIROS]: 5,
      [criteriosIdentificadores.PASES_CORTOS]: 6,
      [criteriosIdentificadores.PASES_LARGOS]: 7,
      [criteriosIdentificadores.CENTROS]: 5,
      [criteriosIdentificadores.CONTROL_BALON]: 7,
      [criteriosIdentificadores.DEFINICION]: 8,
      [criteriosIdentificadores.VELOCIDAD]: 6,
      [criteriosIdentificadores.CREATIVIDAD]: 10,
      [criteriosIdentificadores.AMBIDIESTRO]: 6,
      [criteriosIdentificadores.ALTURA]: 9,
      [criteriosIdentificadores.RENDIMIENTO]: 8,
    },
  },
  {
    nombre: 'Julian Draxler',
    foto: 'card-draxler.png',
    posicion: posicionesIdentificadores.MEDIOCAMPISTA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 10,
      [criteriosIdentificadores.TIROS]: 6,
      [criteriosIdentificadores.PASES_CORTOS]: 5,
      [criteriosIdentificadores.PASES_LARGOS]: 8,
      [criteriosIdentificadores.CENTROS]: 9,
      [criteriosIdentificadores.CONTROL_BALON]: 7,
      [criteriosIdentificadores.DEFINICION]: 8,
      [criteriosIdentificadores.VELOCIDAD]: 8,
      [criteriosIdentificadores.CREATIVIDAD]: 8,
      [criteriosIdentificadores.AMBIDIESTRO]: 7,
      [criteriosIdentificadores.ALTURA]: 7,
      [criteriosIdentificadores.RENDIMIENTO]: 5,
    },
  },
  {
    nombre: 'Cristopher Nkunku',
    foto: 'card-nkunku.png',
    posicion: posicionesIdentificadores.MEDIOCAMPISTA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 9,
      [criteriosIdentificadores.TIROS]: 10,
      [criteriosIdentificadores.PASES_CORTOS]: 4,
      [criteriosIdentificadores.PASES_LARGOS]: 7,
      [criteriosIdentificadores.CENTROS]: 8,
      [criteriosIdentificadores.CONTROL_BALON]: 10,
      [criteriosIdentificadores.DEFINICION]: 8,
      [criteriosIdentificadores.VELOCIDAD]: 4,
      [criteriosIdentificadores.CREATIVIDAD]: 9,
      [criteriosIdentificadores.AMBIDIESTRO]: 9,
      [criteriosIdentificadores.ALTURA]: 10,
      [criteriosIdentificadores.RENDIMIENTO]: 4,
    },
  },
  {
    nombre: 'Adrien Rabiot',
    foto: 'card-rabiot.png',
    posicion: posicionesIdentificadores.MEDIOCAMPISTA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 8,
      [criteriosIdentificadores.TIROS]: 5,
      [criteriosIdentificadores.PASES_CORTOS]: 7,
      [criteriosIdentificadores.PASES_LARGOS]: 7,
      [criteriosIdentificadores.CENTROS]: 4,
      [criteriosIdentificadores.CONTROL_BALON]: 10,
      [criteriosIdentificadores.DEFINICION]: 4,
      [criteriosIdentificadores.VELOCIDAD]: 8,
      [criteriosIdentificadores.CREATIVIDAD]: 9,
      [criteriosIdentificadores.AMBIDIESTRO]: 4,
      [criteriosIdentificadores.ALTURA]: 7,
      [criteriosIdentificadores.RENDIMIENTO]: 8,
    },
  },
  {
    nombre: 'Antoine Bernede',
    foto: 'card-bernede.png',
    posicion: posicionesIdentificadores.MEDIOCAMPISTA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 6,
      [criteriosIdentificadores.TIROS]: 4,
      [criteriosIdentificadores.PASES_CORTOS]: 5,
      [criteriosIdentificadores.PASES_LARGOS]: 5,
      [criteriosIdentificadores.CENTROS]: 6,
      [criteriosIdentificadores.CONTROL_BALON]: 5,
      [criteriosIdentificadores.DEFINICION]: 5,
      [criteriosIdentificadores.VELOCIDAD]: 7,
      [criteriosIdentificadores.CREATIVIDAD]: 7,
      [criteriosIdentificadores.AMBIDIESTRO]: 4,
      [criteriosIdentificadores.ALTURA]: 8,
      [criteriosIdentificadores.RENDIMIENTO]: 4,
    },
  },
  {
    nombre: 'Yacine Adli',
    foto: 'card-adli.png',
    posicion: posicionesIdentificadores.MEDIOCAMPISTA,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 5,
      [criteriosIdentificadores.TIROS]: 4,
      [criteriosIdentificadores.PASES_CORTOS]: 9,
      [criteriosIdentificadores.PASES_LARGOS]: 10,
      [criteriosIdentificadores.CENTROS]: 5,
      [criteriosIdentificadores.CONTROL_BALON]: 5,
      [criteriosIdentificadores.DEFINICION]: 10,
      [criteriosIdentificadores.VELOCIDAD]: 7,
      [criteriosIdentificadores.CREATIVIDAD]: 8,
      [criteriosIdentificadores.AMBIDIESTRO]: 6,
      [criteriosIdentificadores.ALTURA]: 7,
      [criteriosIdentificadores.RENDIMIENTO]: 4,
    },
  },
  {
    nombre: 'Kylian Mbappé',
    posicion: posicionesIdentificadores.DELANTERO,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 10,
      [criteriosIdentificadores.TIROS]: 9,
      [criteriosIdentificadores.PASES_CORTOS]: 5,
      [criteriosIdentificadores.PASES_LARGOS]: 7,
      [criteriosIdentificadores.CENTROS]: 5,
      [criteriosIdentificadores.CONTROL_BALON]: 8,
      [criteriosIdentificadores.DEFINICION]: 10,
      [criteriosIdentificadores.VELOCIDAD]: 8,
      [criteriosIdentificadores.CREATIVIDAD]: 8,
      [criteriosIdentificadores.AMBIDIESTRO]: 5,
      [criteriosIdentificadores.ALTURA]: 10,
      [criteriosIdentificadores.RENDIMIENTO]: 9,
    },
  },
  {
    nombre: 'Kylian Mbappé',
    posicion: posicionesIdentificadores.DELANTERO,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 5,
      [criteriosIdentificadores.TIROS]: 10,
      [criteriosIdentificadores.PASES_CORTOS]: 5,
      [criteriosIdentificadores.PASES_LARGOS]: 8,
      [criteriosIdentificadores.CENTROS]: 8,
      [criteriosIdentificadores.CONTROL_BALON]: 6,
      [criteriosIdentificadores.DEFINICION]: 4,
      [criteriosIdentificadores.VELOCIDAD]: 6,
      [criteriosIdentificadores.CREATIVIDAD]: 9,
      [criteriosIdentificadores.AMBIDIESTRO]: 9,
      [criteriosIdentificadores.ALTURA]: 4,
      [criteriosIdentificadores.RENDIMIENTO]: 4,
    },
  },
  {
    nombre: 'Edinson Cavani',
    posicion: posicionesIdentificadores.DELANTERO,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 9,
      [criteriosIdentificadores.TIROS]: 9,
      [criteriosIdentificadores.PASES_CORTOS]: 7,
      [criteriosIdentificadores.PASES_LARGOS]: 4,
      [criteriosIdentificadores.CENTROS]: 6,
      [criteriosIdentificadores.CONTROL_BALON]: 8,
      [criteriosIdentificadores.DEFINICION]: 9,
      [criteriosIdentificadores.VELOCIDAD]: 10,
      [criteriosIdentificadores.CREATIVIDAD]: 7,
      [criteriosIdentificadores.AMBIDIESTRO]: 6,
      [criteriosIdentificadores.ALTURA]: 5,
      [criteriosIdentificadores.RENDIMIENTO]: 7,
    },
  },
  {
    nombre: 'Neymar Jr',
    posicion: posicionesIdentificadores.DELANTERO,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 6,
      [criteriosIdentificadores.TIROS]: 8,
      [criteriosIdentificadores.PASES_CORTOS]: 8,
      [criteriosIdentificadores.PASES_LARGOS]: 4,
      [criteriosIdentificadores.CENTROS]: 7,
      [criteriosIdentificadores.CONTROL_BALON]: 8,
      [criteriosIdentificadores.DEFINICION]: 7,
      [criteriosIdentificadores.VELOCIDAD]: 10,
      [criteriosIdentificadores.CREATIVIDAD]: 9,
      [criteriosIdentificadores.AMBIDIESTRO]: 10,
      [criteriosIdentificadores.ALTURA]: 6,
      [criteriosIdentificadores.RENDIMIENTO]: 5,
    },
  },
  {
    nombre: 'Eric-Maxim Choupo-Moting',
    posicion: posicionesIdentificadores.DELANTERO,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 10,
      [criteriosIdentificadores.TIROS]: 5,
      [criteriosIdentificadores.PASES_CORTOS]: 5,
      [criteriosIdentificadores.PASES_LARGOS]: 9,
      [criteriosIdentificadores.CENTROS]: 7,
      [criteriosIdentificadores.CONTROL_BALON]: 8,
      [criteriosIdentificadores.DEFINICION]: 10,
      [criteriosIdentificadores.VELOCIDAD]: 4,
      [criteriosIdentificadores.CREATIVIDAD]: 4,
      [criteriosIdentificadores.AMBIDIESTRO]: 9,
      [criteriosIdentificadores.ALTURA]: 8,
      [criteriosIdentificadores.RENDIMIENTO]: 6,
    },
  },
  {
    nombre: 'Timothy Weah',
    posicion: posicionesIdentificadores.DELANTERO,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 6,
      [criteriosIdentificadores.TIROS]: 10,
      [criteriosIdentificadores.PASES_CORTOS]: 10,
      [criteriosIdentificadores.PASES_LARGOS]: 5,
      [criteriosIdentificadores.CENTROS]: 4,
      [criteriosIdentificadores.CONTROL_BALON]: 7,
      [criteriosIdentificadores.DEFINICION]: 5,
      [criteriosIdentificadores.VELOCIDAD]: 4,
      [criteriosIdentificadores.CREATIVIDAD]: 4,
      [criteriosIdentificadores.AMBIDIESTRO]: 8,
      [criteriosIdentificadores.ALTURA]: 6,
      [criteriosIdentificadores.RENDIMIENTO]: 9,
    },
  },
  {
    nombre: 'Moussa Diaby',
    posicion: posicionesIdentificadores.DELANTERO,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 7,
      [criteriosIdentificadores.TIROS]: 8,
      [criteriosIdentificadores.PASES_CORTOS]: 4,
      [criteriosIdentificadores.PASES_LARGOS]: 8,
      [criteriosIdentificadores.CENTROS]: 4,
      [criteriosIdentificadores.CONTROL_BALON]: 4,
      [criteriosIdentificadores.DEFINICION]: 10,
      [criteriosIdentificadores.VELOCIDAD]: 4,
      [criteriosIdentificadores.CREATIVIDAD]: 7,
      [criteriosIdentificadores.AMBIDIESTRO]: 10,
      [criteriosIdentificadores.ALTURA]: 9,
      [criteriosIdentificadores.RENDIMIENTO]: 6,
    },
  },
  {
    nombre: 'Jessé',
    posicion: posicionesIdentificadores.DELANTERO,
    puntajes: {
      [criteriosIdentificadores.SALTOS_CABECEAR]: 6,
      [criteriosIdentificadores.TIROS]: 5,
      [criteriosIdentificadores.PASES_CORTOS]: 9,
      [criteriosIdentificadores.PASES_LARGOS]: 6,
      [criteriosIdentificadores.CENTROS]: 8,
      [criteriosIdentificadores.CONTROL_BALON]: 9,
      [criteriosIdentificadores.DEFINICION]: 5,
      [criteriosIdentificadores.VELOCIDAD]: 4,
      [criteriosIdentificadores.CREATIVIDAD]: 9,
      [criteriosIdentificadores.AMBIDIESTRO]: 9,
      [criteriosIdentificadores.ALTURA]: 7,
      [criteriosIdentificadores.RENDIMIENTO]: 6,
    },
  },
]
